'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import { useState } from 'react'
import { Button } from '@nextui-org/react'
import { SnackbarProvider } from 'notistack'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Storage administration',
  description: 'Generated by Next.js'
}

export default function RootLayout ({ children }) {
  const token = localStorage.getItem('token')
  const [isDarkTheme, setIsDarkTheme] = useState(false)
  const image = 'https://mecaluxes.cdnwm.com/blog/img/tecnicas-almacenamiento.1.2.jpg'

  return (
    <html lang='en' className={`${isDarkTheme ? 'darkMode' : 'lightTheme'}`}>
      <SnackbarProvider maxSnack={3}>
        <body className={`${inter.className}`}>
          <header className='flex justify-between items-center p-4 h-12'>
            {!token &&
              <Image
                src={image}
                alt='background'
                fill
                quality={100}
                priority
                className='shadow-md'
              />}
            <h1 className='relative text-xs md:text-3xl font-extrabold rounded-lg shadow-lg'>
              Storage Administration
            </h1>
            <Button
              onClick={() => setIsDarkTheme(!isDarkTheme)}
              color={`${isDarkTheme ? 'primary' : 'default'}`}
              variant='shadow'
            >
              {isDarkTheme ? 'light' : 'Dark'} Theme
            </Button>
          </header>
          <main className={`${isDarkTheme ? 'darkMode' : 'lightTheme'}`}>
            {children}
          </main>
          {/* Incluir el pie de página aquí si */}
        </body>
      </SnackbarProvider>
    </html>
  )
}
